name: Deploy site
on:
  push:
    paths:
      - "**/*.html"
      - "**/*.css"
      - "**/*.ts"
      - "package*.json"
      - "assets/**"
      - "vendor/**"
      - ".github/workflows/deploy.yml"
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
      - name: Install and build
        run: npm ci && npm run build
      - name: Setup gh pages
        uses: actions/configure-pages@v2
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: dist/
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
