name: Test custom actions in projects repo
on: [workflow_dispatch]
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cwinters8/projects/.github/actions/caller@v0
